name: Terraform Workflow

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose an action (apply or destroy)"
        required: true
        default: "plan"
        type: choice
        options:
          - yes 
          - no

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest
          
      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Terraform Init
      - name: Terraform Init
        run: terraform init -backend-config=backend.hcl

      # Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan

      # Conditional Apply or Destroy
      - name: Execute Terraform Action
        if: ${{ github.event.inputs.action == 'yes' }}
        run: terraform apply -auto-approve

      - name: Execute Terraform Destroy
        if: ${{ github.event.inputs.action == 'yes' }}
        run: terraform destroy -auto-approve
